
spring:
  application:
    name: dscommerce
  profiles:
    active: test
  jpa:
    open-in-view: false

security:
  client-id: ${CLIENT_ID:myclientid}
  client-secret: ${CLIENT_SECRET:myclientsecret}
  jwt:
    duration: ${JWT_DURATION:86400}

cors:
  origins: ${CORS_ORIGINS:http://localhost:8080,http://localhost:5173}


